### ISSUE TITLE
Replace urllib3 by requests

### ISSUE THREAD

**Issue by aleGpereira** [shazow/apiclient#15]
Do you consider a good idea to do that replacement? Since requests lib is considered a very good option to handle http/https communication, i thought it was a good feature to work on.
I'll be working in this for a personal project. If you like this idea, i can maybe send you a pull request once is done.

**Comment by shazow** [comment]
Hi @aleGpereira, thanks for asking but I do not consider this a good idea for the following reasons:

1. This example library (apiclient) was written specifically for urllib3. You're welcome to make a fork of it with requests if you wish. It's only about 40 lines.
2. Requests uses urllib3 underneath. To get the same behaviour, it will take at least as much code to set things up. You'll need to setup a requests session, and you'll need to register a custom urllib3 adapter to configure behaviours like timeouts and retries.
