### ISSUE TITLE
urllib3 not installed

### ISSUE THREAD

**Issue by txsl** [shazow/apiclient#3]
I just called ```pip install apiclient```, which worked fine. But then I tried to run ```import apiclient``` but I was told ```ImportError: No module named urllib3```. Now I see it in setup.py so I don't quite know why it wasn't installed as a dependency with pip.

Just so you're aware of this!

**Comment by franciscod** [comment]
should this be closed?

**Comment by shazow** [comment]
Right you are, thanks!
