### ISSUE TITLE
apiclient isn't verifying HTTPS by default

### ISSUE THREAD

**Issue by franciscod** [shazow/apiclient#6]
Trying to access any https endpoint leads to an exception. This is by design on urllib3: https://urllib3.readthedocs.org/en/latest/security.html

**Comment by franciscod** [comment]
Would you accept a pull request that replaces urllib3 with [requests](http://docs.python-requests.org/en/latest/)?

**Comment by shazow** [comment]
I would accept a pull request which adds certifi as a dependency and sets the pool to use it. :) https://urllib3.readthedocs.org/en/latest/security.html#using-certifi-with-urllib3

**Comment by shazow** [comment]
Fixed in #16
