### ISSUE TITLE
Add python3 support

### ISSUE THREAD

**Issue by Daenyth** [shazow/apiclient#9]
Hopefully it's as easy as running 2to3

```
  File "foo.py", line 6, in <module>
    from apiclient.discovery import build as google_service_build
  File "/home/ubuntu/environment3/lib/python3.4/site-packages/apiclient/__init__.py", line 1, in <module>
    from .base import APIClient, APIClient_SharedSecret
  File "/home/ubuntu/environment3/lib/python3.4/site-packages/apiclient/base.py", line 4, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode'
```

**Comment by shazow** [comment]
What version are you using? We just added py3 support.

**Comment by Daenyth** [comment]
The version from `pip3 install apiclient`

**Comment by Daenyth** [comment]
```
$ pip3 show apiclient
---
Name: apiclient
Version: 1.0.2
Location: /home/ubuntu/environment3/lib/python3.4/site-packages
Requires:
```

**Comment by shazow** [comment]
Ah I lied, we never published a new version of this package, I was thinking of another package I maintain.

Can you try the latest version in master to see if it works?

**Comment by Daenyth** [comment]
Is there an easy way to install that with pip? I'm not super familiar with the distribution tools.

**Comment by shazow** [comment]
Try `pip3 install git+https://github.com/shazow/apiclient`

**Comment by Daenyth** [comment]
```
$ pip3 install --upgrade git+https://github.com/shazow/apiclient
Downloading/unpacking git+https://github.com/shazow/apiclient
  Cloning https://github.com/shazow/apiclient to /tmp/pip-q5qkukzf-build
  Running setup.py (path:/tmp/pip-q5qkukzf-build/setup.py) egg_info for package from git+https://github.com/shazow/apiclient

Requirement already up-to-date: urllib3 in /home/ubuntu/environment3/lib/python3.4/site-packages (from apiclient==1.0.2)
Installing collected packages: apiclient
  Found existing installation: apiclient 1.0.2
    Uninstalling apiclient:
      Successfully uninstalled apiclient
  Running setup.py install for apiclient

Successfully installed apiclient
Cleaning up...
```

When I run nosetests on my app I get

`ImportError: No module named 'apiclient.discovery'`

Did the api change?

**Comment by shazow** [comment]
Possibly? Though I don't recall there ever being a discovery submodule.

Honestly this library is not very maintained anymore. It's very simple in what it does, so I haven't touched it in years.

**Comment by Daenyth** [comment]
I wonder if this project I'm trying to update was actually using another library that happened to have the same name

**Comment by shazow** [comment]
Quite possibly. :)

**Comment by Daenyth** [comment]
Yup, it's this one: https://developers.google.com/api-client-library/python/start/get_started

Thanks for the quick response in any case!
